// Builds the site's pages: public/<name>.html = the shared layout (head, header, phone menu bar,
// footer) + the page's own content from scripts/pages/src/<name>.html.
//   npm run pages
// Edit the files in scripts/pages/, never the generated public/*.html (a test checks they match).
//
// Each source file starts with one line of settings:
//   <!--{"title": "...", "description": "...", "page": "home", "scripts": ["home"], "main": "class"}-->
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SRC = fileURLToPath(new URL("./src/", import.meta.url));
const OUT = fileURLToPath(new URL("../../public/", import.meta.url));

// Top menu (computers) and the bottom menu bar (phones). [page, href, label, short label, icon]
const NAV = [
  ["home", "/", "How it works", "Home", '<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10v9.5h13V10"/><path d="M10 19.5v-5h4v5"/>'],
  ["token", "/token", "Token &amp; holders", "Token", '<circle cx="12" cy="12" r="8.5"/><path d="M12 7.5v9M9.5 9.5h3.75a1.75 1.75 0 0 1 0 3.5h-2.5a1.75 1.75 0 0 0 0 3.5h3.75"/>'],
  ["cities", "/cities", "Claim a city", "Cities", '<path d="M12 21s-6.5-5.6-6.5-11a6.5 6.5 0 0 1 13 0c0 5.4-6.5 11-6.5 11z"/><circle cx="12" cy="10" r="2.4"/>'],
  ["launchpad", "/launchpad", "Launchpad", "Launch", '<path d="M12 3c3 2.2 4.5 5.6 4.5 9.3l-1.8 3.2H9.3l-1.8-3.2C7.5 8.6 9 5.2 12 3z"/><circle cx="12" cy="9.8" r="1.6"/><path d="M9.3 15.5 7 19l3-1M14.7 15.5 17 19l-3-1M12 17.5V21"/>'],
  ["dashboard", "/dashboard", "Dashboard", "Me", '<circle cx="12" cy="8.5" r="3.8"/><path d="M4.5 20c.8-3.8 3.9-6 7.5-6s6.7 2.2 7.5 6"/>'],
];
const icon = (paths) => `<svg viewBox="0 0 24 24" width="22" height="22" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${paths}</svg>`;
const current = (page, p) => (page === p ? ' aria-current="page"' : "");

function layout({ title, description, page, scripts = [], main = "" }, body) {
  const nav = NAV.map(([p, href, label]) => `        <a href="${href}"${current(page, p)}>${label}${p === "launchpad" ? ' <span class="nav__soon">Nov 10</span>' : ""}</a>`).join("\n");
  const tabs = NAV.map(([p, href, , short, paths]) => `    <a href="${href}"${current(page, p)}>${icon(paths)}<span>${short}</span></a>`).join("\n");
  const js = ["site", ...scripts].map((s) => `  <script src="/${s}.js" defer></script>`).join("\n");
  const fullTitle = page === "home" ? "Vicinity — One city. One coin. One community." : `${title} · Vicinity`;
  return `<!doctype html>
<!-- Generated by scripts/pages/build.mjs from scripts/pages/src/${page === "home" ? "index" : page}.html. Edit those, then run: npm run pages -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>${fullTitle}</title>
  <meta name="description" content="${description}">
  <meta name="theme-color" content="#070E19">
  <meta name="color-scheme" content="dark light">
  <meta property="og:title" content="${fullTitle}">
  <meta property="og:description" content="${description}">
  <meta property="og:type" content="website">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="preload" href="/fonts/space-grotesk.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="preload" href="/fonts/inter.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="/style.css">
  <script src="/theme.js"></script>
</head>
<body data-page="${page}">
  <a class="skip" href="#main">Skip to content</a>

  <header class="site-header">
    <div class="wrap site-header__inner">
      <a class="brand" href="/" aria-label="Vicinity home">
        <img src="/logo.svg" alt="" width="30" height="30">
        <span>Vicinity</span>
      </a>
      <nav class="nav" aria-label="Main">
${nav}
      </nav>
      <div class="site-header__actions">
        <button class="theme-toggle" type="button" data-theme-toggle aria-label="Switch to light mode" aria-pressed="false"><span class="moon" aria-hidden="true">☾</span><span class="sun" aria-hidden="true">☀</span></button>
        <a class="btn btn--primary btn--sm account-btn" href="/connect" data-account><span class="btn__dot" aria-hidden="true"></span><span data-account-label>Connect</span></a>
      </div>
    </div>
  </header>

  <main id="main"${main ? ` class="${main}"` : ""}>
${body.trimEnd()}
  </main>

  <footer class="site-footer">
    <div class="wrap footer-grid">
      <div class="footer-brand">
        <div class="brand"><img src="/logo.svg" alt="" width="28" height="28"><span>Vicinity</span></div>
        <p class="muted">One city. One coin. One community.</p>
        <p class="muted small">System status: <span id="status">checking…</span></p>
      </div>
      <nav class="footer-links" aria-label="Footer">
        <p class="footer-title">Explore</p>
        <a href="/">How it works</a><a href="/token">Token &amp; holders</a><a href="/token#verify">Check a wallet's rank</a><a href="/cities">Claim a city</a><a href="/launchpad">Launchpad</a><a href="/dashboard">Dashboard</a>
      </nav>
      <nav class="footer-links" aria-label="Safety">
        <p class="footer-title">Stay safe</p>
        <a href="/token#check">Is this link official?</a><a href="/#faq">FAQ</a><a href="/connect">Connect a wallet</a>
        <p class="tiny muted">Vicinity will never ask for your recovery phrase or private key.</p>
      </nav>
      <div class="footer-links">
        <p class="footer-title">Data</p>
        <p class="tiny muted">Places: <a href="https://www.geonames.org/" target="_blank" rel="noopener">GeoNames</a> (CC BY 4.0). City boundaries: © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a> (ODbL). Country outlines: Natural Earth.</p>
      </div>
    </div>
    <p class="wrap tiny muted footer-legal">vicinitycity.net · Nothing here is financial advice. Meme coins are very risky: only use money you can afford to lose.</p>
  </footer>

  <nav class="tabbar" aria-label="Main (phone)">
${tabs}
  </nav>

  <div class="toast" id="toast" role="status" aria-live="polite" hidden></div>
${js}
</body>
</html>
`;
}

/** Every page: [output file, html]. */
export function buildPages() {
  const out = [];
  for (const f of readdirSync(SRC).filter((x) => x.endsWith(".html")).sort()) {
    const src = readFileSync(SRC + f, "utf8").replace(/\r\n/g, "\n");
    const m = src.match(/^<!--(\{.*\})-->\n/);
    if (!m) throw new Error(`${f}: first line must be <!--{settings}-->`);
    out.push([f, layout(JSON.parse(m[1]), src.slice(m[0].length))]);
  }
  return out;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  for (const [f, html] of buildPages()) { writeFileSync(OUT + f, html); console.log("page ready:", f); }
}
